#!/usr/bin/perl

while (1) {
  print "Enter 1st number before p: ";
  chomp ($aPreP = <>);
  $aPreP =~ /q/ && last;
  print "Enter 1st number after p: ";
  chomp ($aPostP = <>);
  print "Enter 2nd number before p: ";
  chomp ($bPreP = <>);
  print "Enter 2nd number after p: ";
  chomp ($bPostP = <>);
  print "Enter operator: ";
  chomp ($op = <>);

# calc post-p
  if ($op eq "+") {
    $postPSum = $aPostP + $bPostP;
    if ($postPSum >= 12) {
      $prePInc++;
      $postPSum = $postPSum - 12;
    }
    $prePSum = $aPreP + $bPreP + $prePInc;
    print $prePSum,"p",$postPSum;
    $prePInc = 0;
  } else {
    if ($aPostP < $bPostP) {
      $prePDec++;
      $aPostP = $aPostP + 12;
    }
    $postPDiff = $aPostP - $bPostP;
    $prePDiff = $aPreP - $bPreP - $prePDec;
    print $prePDiff,"p",$postPDiff;
    $prePDec = 0;
  }
  print "\n";
}
